---
abstract: 'A simple Catalyst model to interface with L<ElasticSearch>'
author:
  - 'Devin Austin <dhoss@cpan.org>'
build_requires:
  Test::More: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-Search-ElasticSearch
requires:
  Catalyst: 0
  ElasticSearch: 0
  Moose: 0
resources:
  X_mailing_list: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/catalyst
  homepage: http://code.dhoss.net/catalyst-model-search-elasticsearch
  repository: https://dhoss@github.com/dhoss/catalyst-model-search-elasticsearch.git
version: 0.001
